version: '3.8'
services:
  back:
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - XRP_WALLET_SEED=${XRP_WALLET_SEED}
      - XAMAN_API_KEY=${XAMAN_API_KEY}
      - XAMAN_SECRET_KEY=${XAMAN_SECRET_KEY}
    build:
      context: ./back
    restart: always
    ports:
      - "4000:4000"
    container_name: back
    env_file:
      - .env
    volumes:
      - "./back/:/app"
    depends_on:
      - db
    networks:
      - internal_network
  db:
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    build:
      context: ./db
      args:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_ROOT_PASSWORD
    container_name: db
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - internal_network
networks:
  internal_network: